export const langOut = [
  {value: 'it', name: '意大利语  Italian'},
  {value: 'en', name: '英文  English'},
  {value: 'zh', name: '中文  Chinese'},
  {value: 'jp', name: '日语  Japanese'},
  {value: 'kor', name: '韩语  Korean'},
  {value: 'fra', name: '法语  French'},
  {value: 'spa', name: '西班牙语  Spanish'},
  {value: 'pt', name: '葡萄牙语  Portuguese'},
  {value: 'el', name: '希腊语  Greek'},
  {value: 'de', name: '德语  German'},
  {value: 'ru', name: '俄语  Russian'},
  {value: 'th', name: '泰语  Thai'},
  {value: 'nl', name: '荷兰语  Dutch'},
  {value: 'pl', name: '波兰语  polish'},
  {value: 'dan', name: '丹麦语  Danish'},
  {value: 'fin', name: '芬兰语  Finnish'},
  {value: 'cs', name: '捷克语  Czech'},
  {value: 'swe', name: '瑞典语  Swedish'},
  {value: 'hu', name: '匈牙利语  hun'},
  {value: 'ara', name: '阿拉伯语  Arabic'},
  {value: 'cht', name: '繁体中文  Traditional Chinese'},
]

export const langIn = [
  {value: 'auto', name: '自动检测语言  Auto'},
  {value: 'it', name: '意大利语  Italian'},
  {value: 'en', name: '英文  English'},
  {value: 'zh', name: '中文  Chinese'},
  {value: 'jp', name: '日语  Japanese'},
  {value: 'kor', name: '韩语  Korean'},
  {value: 'fra', name: '法语  French'},
  {value: 'spa', name: '西班牙语  Spanish'},
  {value: 'pt', name: '葡萄牙语  Portuguese'},
  {value: 'el', name: '希腊语  Greek'},
  {value: 'de', name: '德语  German'},
  {value: 'ru', name: '俄语  Russian'},
  {value: 'th', name: '泰语  Thai'},
  {value: 'nl', name: '荷兰语  Dutch'},
  {value: 'pl', name: '波兰语  polish'},
  {value: 'dan', name: '丹麦语  Danish'},
  {value: 'fin', name: '芬兰语  Finnish'},
  {value: 'cs', name: '捷克语  Czech'},
  {value: 'swe', name: '瑞典语  Swedish'},
  {value: 'hu', name: '匈牙利语  hun'},
  {value: 'ara', name: '阿拉伯语  Arabic'},
  {value: 'cht', name: '繁体中文  Traditional Chinese'},
]
