export const langOut = [
  {value: 'zh', name: '中文'},
  {value: 'cht', name: '繁体中文'},
  {value: 'en', name: '英文'},
  {value: 'jp', name: '日语'},
  {value: 'kor', name: '韩语'},
  {value: 'it', name: '意大利语'},
  {value: 'fra', name: '法语'},
  {value: 'spa', name: '西班牙语'},
  {value: 'pt', name: '葡萄牙语'},
  {value: 'el', name: '希腊语'},
  {value: 'de', name: '德语'},
  {value: 'ru', name: '俄语'},
  {value: 'nl', name: '荷兰语'},
  {value: 'pl', name: '波兰语'},
  {value: 'dan', name: '丹麦语'},
  {value: 'fin', name: '芬兰语'},
  {value: 'cs', name: '捷克语'},
  {value: 'swe', name: '瑞典语'},
  {value: 'hu', name: '匈牙利语'},
  {value: 'ara', name: '阿拉伯语'},
  {value: 'th', name: '泰语'}
]

export const langIn = [
  {value: 'auto', name: '自动检测语言'},
  {value: 'zh', name: '中文'},
  {value: 'cht', name: '繁体中文'},
  {value: 'en', name: '英文'},
  {value: 'jp', name: '日语'},
  {value: 'kor', name: '韩语'},
  {value: 'it', name: '意大利语'},
  {value: 'fra', name: '法语'},
  {value: 'spa', name: '西班牙语'},
  {value: 'pt', name: '葡萄牙语'},
  {value: 'el', name: '希腊语'},
  {value: 'de', name: '德语'},
  {value: 'ru', name: '俄语'},
  {value: 'nl', name: '荷兰语'},
  {value: 'pl', name: '波兰语'},
  {value: 'dan', name: '丹麦语'},
  {value: 'fin', name: '芬兰语'},
  {value: 'cs', name: '捷克语'},
  {value: 'swe', name: '瑞典语'},
  {value: 'hu', name: '匈牙利语'},
  {value: 'ara', name: '阿拉伯语'},
  {value: 'th', name: '泰语'}
]
